export default [
    {
        id: 0,
        productName: "Milk",
        productCategory: "Dutch lady milk",
        productPrice: 10,
        productImage: "images/milk.jpg",
    },
    {
        id: 1,
        productName: "Cheese",
        productCategory: "Unique parmesan cheese",
        productPrice: 15,
        productImage: "images/cheese.jpg",
    },
    {
        id: 2,
        productName: "Orange Juice",
        productCategory: "Good for health",
        productPrice: 12,
        productImage: "images/orangejuice.jpg",
    },
    {
        id: 3,
        productName: "Potato Chips",
        productCategory: "Hot and spicy",
        productPrice: 3.65,
        productImage: "images/potatochip.jpg",
    },
    {
        id: 4,
        productName: "Coco crunch",
        productCategory: "Great chocolate flavored wheat breakfast cereal",
        productPrice: 14.90,
        productImage: "images/cococrunch.png",
    },
    {
        id: 5,
        productName: "Chicken nugget",
        productCategory: "Ramly tempura flavoured chicken nugget",
        productPrice: 14.29,
        productImage: "images/nugget.jpg",
    },
    {
        id: 6,
        productName: "Chocolate chip cookies",
        productCategory: "Famous amos baked crunchy cookies",
        productPrice: 29.99,
        productImage: "images/cookies.jpg",
    },
    {
        id: 7,
        productName: "Kinder bueno",
        productCategory: "Wafer covered chocolate and havelnut",
        productPrice: 7.50,
        productImage: "images/kinderbueno.jpg",
    },
    {
        id: 8,
        productName: "Chahos tortilla chips",
        productCategory: "Chachos tortilla corn chips bbq bonanza flavour ",
        productPrice: 3.50,
        productImage: "images/chachos.jpg",
    },
    {
        id: 9,
        productName: "Garretts popcorn",
        productCategory: "Caramel popcorn that delights your sweet tooth",
        productPrice: 21.00,
        productImage: "images/popcorn.jpg",
    },
    {
        id: 10,
        productName: "Cadbury chocolate",
        productCategory: "High and rich in dairy and chocolate",
        productPrice: 5.02,
        productImage: "images/cadbury.jpg",
    },
    {
        id: 11,
        productName: "Sunflower kernel",
        productCategory: "Tong garden honey sunflower kernel",
        productPrice: 1.85,
        productImage: "images/sunflowerseed.jpg",
    },
    {
        id: 12,
        productName: "Rasberry jam",
        productCategory: "Grandessa seedless rasberry jam",
        productPrice: 5.45,
        productImage: "images/rasberryjam.png",
    },
    {
        id: 13,
        productName: "Pepero biscuit sticks",
        productCategory: "White chocolate",
        productPrice: 4.30,
        productImage: "images/peperowhite.jpg",
    },
    {
        id: 14,
        productName: "Pepsi bottle",
        productCategory: "Carbonated soft drink",
        productPrice: 4.50,
        productImage: "images/pepsi.jpg",
    },
    {
        id: 15,
        productName: "Dynamite candy",
        productCategory: "Choco filled mint flavoured candy",
        productPrice: 2.00,
        productImage: "images/dynamite.jpg",
    }
]