export default [
    {
        id: 0,
        title: "Milk",
        description: "Dutch lady milk",
        price: 10,
        coverimg: "milk.jpg",
        available: 30,
        quantity: 1,
    },
    {
        id: 1,
        title: "Cheese",
        description: "Unique parmesan cheese",
        price: 15,
        coverimg: "cheese.jpg",
        available: 25,
        quantity: 1,
    },
    {
        id: 2,
        title: "Orange Juice",
        description: "Good for health",
        price: 12,
        coverimg: "orangejuice.jpg",
        available: 0,
        quantity: 1,
    },
    {
        id: 3,
        title: "Potato Chips",
        description: "Hot and spicy",
        price: 3.65,
        coverimg: "potatochip.jpg",
        available: 20,
        quantity: 1,
    },
    {
        id: 4,
        title: "Coco crunch",
        description: "Great chocolate flavored wheat breakfast cereal",
        price: 14.90,
        coverimg: "cococrunch.png",
        available: 5,
        quantity: 1,
    },
    {
        id: 5,
        title: "Chicken nugget",
        description: "Ramly tempura flavoured chicken nugget",
        price: 14.29,
        coverimg: "nugget.jpg",
        available: 30,
        quantity: 1,
    },
    {
        id: 6,
        title: "Chocolate chip cookies",
        description: "Famous amos baked crunchy cookies",
        price: 29.99,
        coverimg: "cookies.jpg",
        available: 12,
        quantity: 1,
    },
    {
        id: 7,
        title: "Kinder bueno",
        description: "Wafer covered chocolate and havelnut",
        price: 7.50,
        coverimg: "kinderbueno.jpg",
        available: 25,
        quantity: 1,
    },
    {
        id: 8,
        title: "Chahos tortilla chips",
        description: "Chachos tortilla corn chips bbq bonanza flavour ",
        price: 3.50,
        coverimg: "chachos.jpg",
        available: 2,
        quantity: 1,
    },
    {
        id: 9,
        title: "Garretts popcorn",
        description: "Caramel popcorn that delights your sweet tooth",
        price: 21.00,
        coverimg: "popcorn.jpg",
        available: 18,
        quantity: 1,
    },
    {
        id: 10,
        title: "Cadbury chocolate",
        description: "High and rich in dairy and chocolate",
        price: 5.02,
        coverimg: "cadbury.jpg",
        available: 0,
        quantity: 1,
    },
    {
        id: 11,
        title: "Tong garden sunflower kernel",
        description: "Honey sunflower kernel",
        price: 1.85,
        coverimg: "sunflowerseed.jpg",
        available: 22,
        quantity: 1,
    },
    {
        id: 12,
        title: "Rasberry jam",
        description: "Grandessa seedless rasberry jam",
        price: 5.45,
        coverimg: "rasberryjam.png",
        available: 13,
        quantity: 1,
    },
    {
        id: 13,
        title: "Pepero biscuit sticks",
        description: "White chocolate",
        price: 4.30,
        coverimg: "peperowhite.jpg",
        available: 1,
        quantity: 1,
    },
    {
        id: 14,
        title: "Pepsi bottle",
        description: "Carbonated soft drink",
        price: 4.50,
        coverimg: "pepsi.jpg",
        available: 3,
        quantity: 1,
    },
    {
        id: 15,
        title: "Dynamite candy",
        description: "Choco filled mint flavoured candy",
        price: 2.00,
        coverimg: "dynamite.jpg",
        available: 33,
        quantity: 1,
    }
    
    
]